<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXL0BVL5\srcApp_KernelBrefapp2DebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXL0BVL5/srcApp_KernelBrefapp2DebugContainer.php') {
    touch(__DIR__.'/ContainerXL0BVL5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelBrefapp2DebugContainer::class, false)) {
    \class_alias(\ContainerXL0BVL5\srcApp_KernelBrefapp2DebugContainer::class, srcApp_KernelBrefapp2DebugContainer::class, false);
}

return new \ContainerXL0BVL5\srcApp_KernelBrefapp2DebugContainer([
    'container.build_hash' => 'XL0BVL5',
    'container.build_id' => '1f9cb180',
    'container.build_time' => 1573659014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXL0BVL5');
