<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5PHyrK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5PHyrK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX5PHyrK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX5PHyrK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX5PHyrK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X5PHyrK',
    'container.build_id' => '7865f40b',
    'container.build_time' => 1574240031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5PHyrK');
