<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8ZJYuJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8ZJYuJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8ZJYuJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8ZJYuJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU8ZJYuJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U8ZJYuJ',
    'container.build_id' => '96d3e344',
    'container.build_time' => 1574849788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8ZJYuJ');
