<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'actus' => [[], ['_controller' => 'App\\Controller\\ActusController::index'], [], [['text', '/actus']], [], []],
    'app_actus_update' => [['id'], ['_controller' => 'App\\Controller\\ActusController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/edit']], [], []],
    'aidants' => [[], ['_controller' => 'App\\Controller\\AidantsController::index'], [], [['text', '/aidants']], [], []],
    'app_aidants_update' => [['id'], ['_controller' => 'App\\Controller\\AidantsController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/edit']], [], []],
    'patients' => [[], ['_controller' => 'App\\Controller\\PatientsController::index'], [], [['text', '/patients']], [], []],
    'ajout_article' => [[], ['_controller' => 'App\\Controller\\PatientsController::createArticle'], [], [['text', '/article/ajout']], [], []],
    'article_show' => [['id'], ['_controller' => 'App\\Controller\\PatientsController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'app_patients_update' => [['id'], ['_controller' => 'App\\Controller\\PatientsController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article/edit']], [], []],
];
